<p style="font-family: Arial; font-size:3em;color:black;"> Lab W1 </p>

Students name in this Group:
1) Shem
2) Dhvanil
3) Deepak
4) Sai
5) Tina Jacob

In [1]:
# importing numpy
import numpy as np

In [44]:
# Create a numpy array with the elements "1, 2, 3, 5, 0", print the array and test if all of its elements are non-zero.
array_A = np.array([1, 2, 3, 5, 0])
print(array_A)

non_zero_counter=0

for i in range(len(array_A)):
    if array_A[i]!=0:
        non_zero_counter+=1
        
    else:
        continue

print('There are ',non_zero_counter,'non zero values in the array')

[1 2 3 5 0]
There are  4 non zero values in the array


In [45]:
# Create a numpy array with the elements "3, -1, 3, 7, 2", print the array and test if any of its elements is non-zero.
array_B = np.array([3, -1, 3, 7, 2])
print(array_B)

non_zero_counter=0

for i in range(len(array_B)):
    if array_B[i]!=0:
        non_zero_counter+=1
        
    else:
        continue

print('There are ',non_zero_counter,'non zero values in the array')

[ 3 -1  3  7  2]
There are  5 non zero values in the array


In [46]:
# Create a numpy array with the elements "0, 0, 0, 0", print the array and test if any of its elements is non-zero.
array_C=np.zeros(4,int)
print(array_C)

non_zero_counter=0

for i in range(len(array_C)):
    if array_C[i]!=0:
        non_zero_counter+=1
        
    else:
        continue

print('There are ',non_zero_counter,'non zero values in the arraay')

[0 0 0 0]
There are  0 non zero values in the arraay


In [48]:
# Create a numpy array with the elements "56, -2, 7", print the array and the amount of memory required to store it.
array_D = np.array([56, -2, 7])
print(array_D)

print('Memory required in bytes :',array_D.nbytes)

[56 -2  7]
Memory required in bytes : 12


In [43]:
# Create a numpy array with 10 zeros and print the array.

array_E=np.zeros(10,int)
print(array_E)

# Create a numpy array with 6 ones and print the array.

array_F=np.ones(6,int)
print(array_F)

# Create a numpy array with 12 '3's and print the array. [3 3 3 3 3 3 3 3 3 3 3 3]

array_G=np.array([3,3,3,3,3,3,3,3,3,3,3,3])
print(array_G)


[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1]
[3 3 3 3 3 3 3 3 3 3 3 3]


In [52]:
# Create a numpy array of the integers from 8 to 20 and print the array. (make sure 20 itself is included) 
#hint:  use "arange" method

array_H = np.arange(8,21,1)
print(array_H)

# Create a numpy array of the even integers from 8 to 20 and print the array. (make sure 20 itself is included)   
#hint:  use "arange" method

array_H = np.arange(8,21,2)
print(array_H)

[ 8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 8 10 12 14 16 18 20]


In [60]:
# Create a numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5. 
#Print the mean, max, min and std of the array.

a = np.random.normal(loc=2, scale=0.5, size=100)

print(a)

a_mean = np.mean (a)
print ("the mean is:", a_mean)

a_max = np.max (a)
print ("the max is:", a_max)

a_min = np.min (a)
print ("the min is:", a_min)

a_std = np.std (a)
print ("the std is:", a_std)



[1.86226726 2.78669029 2.42488173 1.77752214 2.10087805 2.4993602
 2.26131321 2.27682911 2.13559256 2.44978908 2.01037121 1.61866427
 1.2853163  1.87898932 2.76242986 1.43367904 1.68358647 2.06351786
 2.33519474 2.52049903 1.4917453  2.40980667 2.30927116 1.76612304
 1.60915811 2.25400192 2.72300712 1.87653771 2.17390271 2.43979248
 2.05520267 2.08590817 2.91297436 1.82335986 2.63740579 1.79698072
 2.27178556 2.33015609 1.83077665 1.28694406 1.67472787 1.92258756
 2.26066688 1.88483262 2.18251352 2.3592544  2.14808669 1.46198791
 1.74775545 1.94825629 1.48896415 2.5778971  1.95686707 1.33070354
 2.25019481 2.01629516 2.9866191  2.49318178 1.73224    2.66249808
 2.03370449 1.47065159 2.26030558 2.52873086 1.6331778  2.07301507
 1.7499722  1.71659183 2.53389815 1.3533208  2.95581996 2.38221071
 2.42615383 1.75508475 1.83030209 2.10506142 1.95554012 1.59205505
 1.79196158 1.30759274 1.76201208 2.88501288 2.61790975 2.16820767
 2.0823791  1.72601014 1.82559387 2.01565784 2.22676894 2.26811

In [59]:
# Create a numpy array consisting of 1000 random elements from normal distribution with mean of 2 and std of 0.5. 
#Print the mean, max, min and std of the array.


b = np.random.normal(loc=2, scale=0.5, size=1000)

print(b)

b_mean = np.mean (b)
print ("the mean is:", b_mean)

b_max = np.max (b)
print ("the max is:", b_max)

b_min = np.min (b)
print ("the min is:", b_min)

b_std = np.std (b)
print ("the std is:", b_std)

[2.47098238 1.90079669 2.15852861 1.66536267 2.52741035 2.48800754
 1.66332437 1.70113875 1.39475904 2.84932289 2.44314333 2.43895963
 2.32976691 1.88043446 1.58966405 1.55849761 2.10996628 2.30371374
 1.9030401  2.10310691 2.88594148 1.48616262 1.45324812 2.34613164
 2.01887384 1.65149137 2.88966807 2.32188228 1.98021341 1.40389995
 1.46372026 2.00791776 1.57692955 1.53065466 1.70899184 2.50655062
 2.37308956 1.87506423 1.68456507 1.7728776  2.06486943 1.80733599
 1.20801296 1.82913532 1.67537783 2.87495558 1.8587353  1.72042674
 2.34854879 1.69763206 2.08544141 1.4976769  2.68070939 2.31947722
 2.56153689 1.83418348 2.40008435 2.15606188 1.36787822 2.49202665
 2.03550974 1.63929389 2.2006457  2.06586395 1.3867236  1.84718422
 1.75628408 1.95059705 1.88199486 2.41102989 2.84445387 1.66459546
 2.34132902 2.07352753 1.71126465 1.58791728 3.38741151 2.258455
 1.80647709 0.94346126 1.64046966 1.61781219 1.59060419 2.55043421
 1.75902292 1.72784642 1.73353136 1.17778879 0.7020649  2.195319

In [58]:
# Create a numpy array consisting of 1000000 random elements from normal distribution with mean of 2 and std of 0.5. 
#Print the mean, max, min and std of the array.

c = np.random.normal(loc=2, scale=0.5, size=1000000)

print(c)

c_mean = np.mean (c)
print ("the mean is:", c_mean)

c_max = np.max (c)
print ("the max is:", c_max)

c_min = np.min (c)
print ("the min is:", c_min)

c_std = np.std (c)
print ("the std is:", c_std)




[2.11720039 2.38792634 1.97226405 ... 1.48513967 2.06552716 2.64010036]
the mean is: 1.9995266616464134
the max is: 4.33752731166075
the min is: -0.6166879201144981
the std is: 0.5006717969613306


### (Bonus question) Looking at the three above examples with 1000, 5000, and 10000 random elements, do you have any observations about mean and std values?

The value of mean apprears to decrease by a small value when the number of elements increased where as the std values doesn't appreat to follow any pattern.

